---
- name: Nginx | Installing Nginx repo rpm
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
- name: Nginx | Installing Nginx
  yum:
    name: nginx
    state: latest
- name: Copy nginx.conf file
  copy:
    src: roles/loadbalancers/files/nginx.conf
    dest: /etc/nginx
    mode: 0644
- name: Nginx | Starting Nginx
  service:
    name: nginx
    state: started
- name: enabling nginx service
  command: /bin/systemctl enable nginx.service
- name: Nginx | Installing Zabbix repo rpm
  yum:
    name: http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
- name: Nginx | Installing Zabbix agent
  yum:
    name: zabbix-agent
    state: latest
- name: enabling zabbix agent service
  command: /bin/systemctl enable zabbix-agent.service
- name: Copy zabbix-agentd.conf file
  copy:
    src: roles/loadbalancers/files/zabbix_agentd.conf
    dest: /etc/zabbix/
    mode: 0644

...
