---
- name: nfs setup  
  yum:
    name: nfs-utils
    state: latest

- name: adding nfs service to firewall  
  command: /bin/firewall-cmd --permanent --zone=public --add-service=nfs

- name: reloading firewall rules
  command: /bin/firewall-cmd --reload
  
- name: copy exports file
  copy:
    src: /home/avalle/roles/nfs/files/exports
    dest: /etc
    mode: 0644
  
- name: starts nfs service
  service:
    name: nfs
    state: started
  
- command: /bin/systemctl enable nfs-server.service
...
