---
- name: Install Apache2
  apt: name=apache2 update_cache=yes state=latest
- name: Copy HTML files
  copy:
    src: "{{ item }}"
    dest: /var/www/html
    mode: 0644
  with_fileglob: 
    - /home/vagrant/demo-playbooks/roles/webservers/files/*
- name: install php packages
  apt: name='{{ item }}' update_cache=yes state=latest
  with_items:
    - mcrypt
    - php5
    - libapache2-mod-php5
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-sqlite
    - sqlite3
- name: Starts Apache2 service
  service: name=apache2 state=started
...
